/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


import Model.NhanVien_ToanCuc;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Label;
import java.awt.Panel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;

/**
 *
 * @author admin
 */
public class Checkin_Panel extends javax.swing.JPanel{

    private Frame Main_View;

    
    public Checkin_Panel() {
        initComponents();
        NhanVien_ToanCuc nv = new NhanVien_ToanCuc();
        int n = 20;//?
        Box_chua.setLayout(new GridLayout(n,1,5,5));

        Panel thanhphan = new Panel();
        thanhphan.setLayout(new GridLayout(1,5));
        thanhphan.setPreferredSize(new Dimension(WIDTH, 40));
        thanhphan.setBackground(Color.WHITE);
        Label lb1 = new Label(nv.getManv());
        Label lb2 = new Label(nv.getTennv());
        Label lb3 = new Label(nv.getSdt());
        Label lb4 = new Label(nv.getCccd());
        Label lb5 = new Label(nv.getChucvu());
        thanhphan.add(lb1);
        thanhphan.add(lb2);
        thanhphan.add(lb3);
        thanhphan.add(lb4);
        thanhphan.add(lb5);
        if(nv.getManv() != null && nv.getTennv() != null && nv.getCccd() != null && nv.getSdt() != null && nv.getChucvu() != null){
            n++;
            Box_chua.setLayout(new GridLayout(n,1,5,5));
            Box_chua.add(thanhphan);
        }
        //---------------------------------------
        
        
               
        for(int i = 0; i < 20; i++){
                Panel tp = new Panel();
                tp.setLayout(new GridLayout(1,6));
                tp.setPreferredSize(new Dimension(WIDTH, 40));
                tp.setBackground(Color.WHITE);
                Label lb11 = new Label("NV20"+i);
                Label lb21 = new Label("Nguyen A "+ i);
                Label lb31 = new Label("123456789" + i);
                Label lb41 = new Label("97654321" + i);
                Label lb51 = new Label("Nhân viên");
                
                Panel chucnang = new Panel(new GridLayout(2, 2,0,2));
   
                JButton but1 = new JButton("Sửa");
                JButton but2 = new JButton("Xóa");
                but1.setBackground(Color.YELLOW);
                but2.setBackground(Color.red);
                chucnang.add(but1);
                chucnang.add(but2);
                
                
                tp.add(lb11);
                tp.add(lb21);
                tp.add(lb31);
                tp.add(lb41);
                tp.add(lb51);
                tp.add(chucnang);
                Box_chua.add(tp);
                tp.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    tp.setBackground(new java.awt.Color(30, 15, 79));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    tp.setBackground(Color.WHITE);
                }
            });
                

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JSCroll = new javax.swing.JScrollPane();
        Box_chua = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 667));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(30, 15, 79));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(30, 15, 79));
        jPanel2.setLayout(new java.awt.GridLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MANV");
        jPanel2.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ tên");
        jPanel2.add(jLabel4);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SĐT");
        jPanel2.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CCCD");
        jPanel2.add(jLabel1);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Chức vụ");
        jPanel2.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Chức năng");
        jPanel2.add(jLabel6);

        Box_chua.setBackground(new java.awt.Color(30, 15, 79));

        javax.swing.GroupLayout Box_chuaLayout = new javax.swing.GroupLayout(Box_chua);
        Box_chua.setLayout(Box_chuaLayout);
        Box_chuaLayout.setHorizontalGroup(
            Box_chuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );
        Box_chuaLayout.setVerticalGroup(
            Box_chuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );

        JSCroll.setViewportView(Box_chua);
        Box_chua.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JSCroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSCroll, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    NewJDialog a = new NewJDialog(Main_View, true);
    a.setLocationRelativeTo(null);
    a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Box_chua;
    private javax.swing.JScrollPane JSCroll;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
