/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class DatTiec_Panel extends javax.swing.JPanel {

    /**
     * Creates new form TrangChu_Panel
     */
    public DatTiec_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MaKhach_Text = new javax.swing.JTextField();
        TenKhach_Text = new javax.swing.JTextField();
        SDTKhach_Text = new javax.swing.JTextField();
        ChonKhach_Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TienCoc_Text = new javax.swing.JTextField();
        ThanhToan_radio = new javax.swing.JRadioButton();
        MaPhong_Box = new javax.swing.JComboBox<>();
        MaTiec_Text = new javax.swing.JTextField();
        SoKhach_Spinner = new javax.swing.JSpinner();
        TongTien_Text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        GhiChu_Text = new javax.swing.JTextArea();
        NgayToChuc_Date = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        DatTiec_button = new javax.swing.JButton();
        Quanlymonan_button = new javax.swing.JButton();
        Taomoi_button = new javax.swing.JButton();
        Tinkiem_button = new javax.swing.JButton();
        ChitietTiec_button = new javax.swing.JButton();
        XuatHoaDon_button = new javax.swing.JButton();
        Xoa_button = new javax.swing.JButton();
        Sua_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_DatTiec = new javax.swing.JTable();

        setBackground(new java.awt.Color(30, 15, 79));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thông tin người đặt");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thông tin tiệc");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Quản lý tiệc");

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã khách hàng");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tên khách hàng");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Số điện thoại");

        MaKhach_Text.setForeground(new java.awt.Color(0, 0, 0));
        MaKhach_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaKhach_TextActionPerformed(evt);
            }
        });

        TenKhach_Text.setForeground(new java.awt.Color(0, 0, 0));
        TenKhach_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenKhach_TextActionPerformed(evt);
            }
        });

        SDTKhach_Text.setForeground(new java.awt.Color(0, 0, 0));
        SDTKhach_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDTKhach_TextActionPerformed(evt);
            }
        });

        ChonKhach_Button.setBackground(new java.awt.Color(51, 102, 255));
        ChonKhach_Button.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ChonKhach_Button.setForeground(new java.awt.Color(255, 255, 255));
        ChonKhach_Button.setText("Chọn khách hàng");
        ChonKhach_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaKhach_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenKhach_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDTKhach_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(ChonKhach_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaKhach_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenKhach_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDTKhach_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(ChonKhach_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Mã tiệc ");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Mã phòng");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ngày tổ chức");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tình trạng");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Số khách");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tiền cọc");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Tổng tiền");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Ghi chú");

        TienCoc_Text.setForeground(new java.awt.Color(0, 0, 0));
        TienCoc_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TienCoc_TextActionPerformed(evt);
            }
        });

        ThanhToan_radio.setForeground(new java.awt.Color(0, 0, 0));
        ThanhToan_radio.setText("Đã thanh toán");
        ThanhToan_radio.setOpaque(false);
        ThanhToan_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThanhToan_radioActionPerformed(evt);
            }
        });

        MaPhong_Box.setForeground(new java.awt.Color(0, 0, 0));
        MaPhong_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D01", "D02", "D03", "D04", "D05", "D06" }));

        MaTiec_Text.setForeground(new java.awt.Color(0, 0, 0));

        TongTien_Text.setForeground(new java.awt.Color(0, 0, 0));
        TongTien_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TongTien_TextActionPerformed(evt);
            }
        });

        GhiChu_Text.setColumns(20);
        GhiChu_Text.setForeground(new java.awt.Color(0, 0, 0));
        GhiChu_Text.setLineWrap(true);
        GhiChu_Text.setRows(5);
        jScrollPane1.setViewportView(GhiChu_Text);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MaPhong_Box, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MaTiec_Text, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SoKhach_Spinner, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TienCoc_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(TongTien_Text)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ThanhToan_radio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NgayToChuc_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaTiec_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaPhong_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(NgayToChuc_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ThanhToan_radio))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SoKhach_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(TienCoc_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TongTien_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 51, 255));

        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(2, 4, 12, 12));

        DatTiec_button.setBackground(new java.awt.Color(51, 102, 255));
        DatTiec_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DatTiec_button.setForeground(new java.awt.Color(255, 255, 255));
        DatTiec_button.setText("Đặt tiệc");
        DatTiec_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatTiec_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(DatTiec_button);

        Quanlymonan_button.setBackground(new java.awt.Color(51, 102, 255));
        Quanlymonan_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Quanlymonan_button.setForeground(new java.awt.Color(255, 255, 255));
        Quanlymonan_button.setText("Quản lý món ăn");
        jPanel4.add(Quanlymonan_button);

        Taomoi_button.setBackground(new java.awt.Color(51, 102, 255));
        Taomoi_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Taomoi_button.setForeground(new java.awt.Color(255, 255, 255));
        Taomoi_button.setText("Tạo mới");
        jPanel4.add(Taomoi_button);

        Tinkiem_button.setBackground(new java.awt.Color(51, 102, 255));
        Tinkiem_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Tinkiem_button.setForeground(new java.awt.Color(255, 255, 255));
        Tinkiem_button.setText("Tìm kiếm");
        jPanel4.add(Tinkiem_button);

        ChitietTiec_button.setBackground(new java.awt.Color(51, 102, 255));
        ChitietTiec_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChitietTiec_button.setForeground(new java.awt.Color(255, 255, 255));
        ChitietTiec_button.setText("Chi tiết tiệc");
        jPanel4.add(ChitietTiec_button);

        XuatHoaDon_button.setBackground(new java.awt.Color(51, 102, 255));
        XuatHoaDon_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        XuatHoaDon_button.setForeground(new java.awt.Color(255, 255, 255));
        XuatHoaDon_button.setText("Xuất hóa đơn");
        jPanel4.add(XuatHoaDon_button);

        Xoa_button.setBackground(new java.awt.Color(51, 102, 255));
        Xoa_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Xoa_button.setForeground(new java.awt.Color(255, 255, 255));
        Xoa_button.setText("Xóa");
        Xoa_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xoa_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(Xoa_button);

        Sua_button.setBackground(new java.awt.Color(51, 102, 255));
        Sua_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Sua_button.setForeground(new java.awt.Color(255, 255, 255));
        Sua_button.setText("Sửa");
        jPanel4.add(Sua_button);

        jScrollPane2.setBackground(new java.awt.Color(204, 255, 255));

        Table_DatTiec.setBackground(new java.awt.Color(204, 255, 255));
        Table_DatTiec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tiệc", "Mã phòng", "Mã khách", "Ngày lập", "Ngày tổ chức", "Tình trạng", "Số khách", "Tiền cọc", "Tổng tiền", "Ghi chú"
            }
        ));
        jScrollPane2.setViewportView(Table_DatTiec);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MaKhach_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaKhach_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaKhach_TextActionPerformed

    private void TenKhach_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenKhach_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenKhach_TextActionPerformed

    private void SDTKhach_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDTKhach_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SDTKhach_TextActionPerformed

    private void TienCoc_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TienCoc_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TienCoc_TextActionPerformed

    private void ThanhToan_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThanhToan_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThanhToan_radioActionPerformed

    private void TongTien_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TongTien_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TongTien_TextActionPerformed

    private void DatTiec_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatTiec_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table_DatTiec.getModel();
        String row[] = new String[10];
        row[0] = MaTiec_Text.getText();
//        row[3] = "3";
//        row[4] = "";
//        row[5] = "3";
//        row[6] = "3";
//        row[7] = "3";
//        row[8] = "3";
//        row[9] = "3";
        
        model.addRow(row);
        Table_DatTiec.setModel(model);
    
    }//GEN-LAST:event_DatTiec_buttonActionPerformed

    private void Xoa_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xoa_buttonActionPerformed
        int indext = Table_DatTiec.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) Table_DatTiec.getModel();
        model.removeRow(indext);
    }//GEN-LAST:event_Xoa_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChitietTiec_button;
    private javax.swing.JButton ChonKhach_Button;
    private javax.swing.JButton DatTiec_button;
    private javax.swing.JTextArea GhiChu_Text;
    private javax.swing.JTextField MaKhach_Text;
    private javax.swing.JComboBox<String> MaPhong_Box;
    private javax.swing.JTextField MaTiec_Text;
    private com.toedter.calendar.JDateChooser NgayToChuc_Date;
    private javax.swing.JButton Quanlymonan_button;
    private javax.swing.JTextField SDTKhach_Text;
    private javax.swing.JSpinner SoKhach_Spinner;
    private javax.swing.JButton Sua_button;
    private javax.swing.JTable Table_DatTiec;
    private javax.swing.JButton Taomoi_button;
    private javax.swing.JTextField TenKhach_Text;
    private javax.swing.JRadioButton ThanhToan_radio;
    private javax.swing.JTextField TienCoc_Text;
    private javax.swing.JButton Tinkiem_button;
    private javax.swing.JTextField TongTien_Text;
    private javax.swing.JButton Xoa_button;
    private javax.swing.JButton XuatHoaDon_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
