/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Bean.DanhMuc;
import Controller.ChuyenManHinh_Controller;
import Controller.Logout_controller;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author admin
 */
public class Main_View extends javax.swing.JFrame {
    /**
     * Creates new form TrangChu_Frame
     */
    public Main_View() {
//        this.setUndecorated(true);
        initComponents();
        
        ChuyenManHinh_Controller controller = new ChuyenManHinh_Controller(MainView_Panel);
        controller.setView(Panel_TrangChu,Label_Trangchu);
        
        List<DanhMuc> listItem = new ArrayList<>();
        
        listItem.add(new DanhMuc("TrangChu",Panel_TrangChu,Label_Trangchu));
        listItem.add(new DanhMuc("QuanLiKhachHang",Panel_Quanlykhachhang,Label_Quanlykhachhang));
        listItem.add(new DanhMuc("QuanLiPhong",Panel_Quanlyphong,Label_Quanlyphong));
        listItem.add(new DanhMuc("QuanLiDichVu",Panel_Quanlydichvu,Label_Quanlydichvu));
        listItem.add(new DanhMuc("DatTiec",Panel_Dattiec,Label_DatTiec));
        listItem.add(new DanhMuc("QuanLiDatPhong",Panel_DatPhong,Label_DatPhong));
        listItem.add(new DanhMuc("CheckIn",Panel_CheckIn,Label_Checkin));
        listItem.add(new DanhMuc("CheckOut",Panel_CheckOut,Label_Checkout));
        listItem.add(new DanhMuc("DangXuat", Panel_TaiKhoan, Label_TaiKhoan));
        listItem.add(new DanhMuc("ThanhFix",Thanh_Fix_Panel, Thanh_Fix_Label));
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_TrangChu = new javax.swing.JPanel();
        Label_Trangchu = new javax.swing.JLabel();
        Panel_Quanlyphong = new javax.swing.JPanel();
        Label_Quanlyphong = new javax.swing.JLabel();
        Panel_Quanlykhachhang = new javax.swing.JPanel();
        Label_Quanlykhachhang = new javax.swing.JLabel();
        Panel_Quanlydichvu = new javax.swing.JPanel();
        Label_Quanlydichvu = new javax.swing.JLabel();
        Panel_Dattiec = new javax.swing.JPanel();
        Label_DatTiec = new javax.swing.JLabel();
        Panel_DatPhong = new javax.swing.JPanel();
        Label_DatPhong = new javax.swing.JLabel();
        Panel_CheckIn = new javax.swing.JPanel();
        Label_Checkin = new javax.swing.JLabel();
        Panel_CheckOut = new javax.swing.JPanel();
        Label_Checkout = new javax.swing.JLabel();
        Panel_TaiKhoan = new javax.swing.JPanel();
        Label_TaiKhoan = new javax.swing.JLabel();
        Thanh_Fix_Panel = new javax.swing.JPanel();
        Thanh_Fix_Label = new javax.swing.JLabel();
        Panel_Logout = new javax.swing.JPanel();
        Lable_LogOut = new javax.swing.JLabel();
        MainView_Panel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        Search_Text2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 22, 89));

        jPanel2.setBackground(new java.awt.Color(30, 15, 79));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(137, 64, 231)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo_main.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("       JU-AT HOTEL  ");

        Panel_TrangChu.setBackground(new java.awt.Color(30, 15, 79));
        Panel_TrangChu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_TrangChuMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel_TrangChuMouseMoved(evt);
            }
        });
        Panel_TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_TrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_TrangChuMouseExited(evt);
            }
        });

        Label_Trangchu.setBackground(new java.awt.Color(30, 15, 79));
        Label_Trangchu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Trangchu.setForeground(new java.awt.Color(169, 170, 255));
        Label_Trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home2.png"))); // NOI18N
        Label_Trangchu.setText("   Trang chủ");
        Label_Trangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_TrangchuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_TrangchuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_TrangChuLayout = new javax.swing.GroupLayout(Panel_TrangChu);
        Panel_TrangChu.setLayout(Panel_TrangChuLayout);
        Panel_TrangChuLayout.setHorizontalGroup(
            Panel_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TrangChuLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(Label_Trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_TrangChuLayout.setVerticalGroup(
            Panel_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Panel_Quanlyphong.setBackground(new java.awt.Color(30, 15, 79));

        Label_Quanlyphong.setBackground(new java.awt.Color(30, 15, 79));
        Label_Quanlyphong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Quanlyphong.setForeground(new java.awt.Color(169, 170, 255));
        Label_Quanlyphong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Users-2.24.png"))); // NOI18N
        Label_Quanlyphong.setText("   Quản lý phòng");
        Label_Quanlyphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_QuanlyphongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_QuanlyphongMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_QuanlyphongLayout = new javax.swing.GroupLayout(Panel_Quanlyphong);
        Panel_Quanlyphong.setLayout(Panel_QuanlyphongLayout);
        Panel_QuanlyphongLayout.setHorizontalGroup(
            Panel_QuanlyphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_QuanlyphongLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(Label_Quanlyphong, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_QuanlyphongLayout.setVerticalGroup(
            Panel_QuanlyphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Quanlyphong, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Panel_Quanlykhachhang.setBackground(new java.awt.Color(30, 15, 79));

        Label_Quanlykhachhang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Quanlykhachhang.setForeground(new java.awt.Color(169, 170, 255));
        Label_Quanlykhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Users-2.24.png"))); // NOI18N
        Label_Quanlykhachhang.setText("   Quản lý khách hàng");
        Label_Quanlykhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_QuanlykhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_QuanlykhachhangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_QuanlykhachhangLayout = new javax.swing.GroupLayout(Panel_Quanlykhachhang);
        Panel_Quanlykhachhang.setLayout(Panel_QuanlykhachhangLayout);
        Panel_QuanlykhachhangLayout.setHorizontalGroup(
            Panel_QuanlykhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_QuanlykhachhangLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(Label_Quanlykhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_QuanlykhachhangLayout.setVerticalGroup(
            Panel_QuanlykhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Quanlykhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Panel_Quanlydichvu.setBackground(new java.awt.Color(30, 15, 79));

        Label_Quanlydichvu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Quanlydichvu.setForeground(new java.awt.Color(169, 170, 255));
        Label_Quanlydichvu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Users-2.24.png"))); // NOI18N
        Label_Quanlydichvu.setText("   Quản lý dịch vụ");
        Label_Quanlydichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_QuanlydichvuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_QuanlydichvuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_QuanlydichvuLayout = new javax.swing.GroupLayout(Panel_Quanlydichvu);
        Panel_Quanlydichvu.setLayout(Panel_QuanlydichvuLayout);
        Panel_QuanlydichvuLayout.setHorizontalGroup(
            Panel_QuanlydichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_QuanlydichvuLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(Label_Quanlydichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_QuanlydichvuLayout.setVerticalGroup(
            Panel_QuanlydichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Quanlydichvu, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Panel_Dattiec.setBackground(new java.awt.Color(30, 15, 79));

        Label_DatTiec.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_DatTiec.setForeground(new java.awt.Color(169, 170, 255));
        Label_DatTiec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Users-2.24.png"))); // NOI18N
        Label_DatTiec.setText("   Đặt tiệc");
        Label_DatTiec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_DatTiecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_DatTiecMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_DattiecLayout = new javax.swing.GroupLayout(Panel_Dattiec);
        Panel_Dattiec.setLayout(Panel_DattiecLayout);
        Panel_DattiecLayout.setHorizontalGroup(
            Panel_DattiecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DattiecLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(Label_DatTiec, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_DattiecLayout.setVerticalGroup(
            Panel_DattiecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_DatTiec, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Panel_DatPhong.setBackground(new java.awt.Color(30, 15, 79));

        Label_DatPhong.setBackground(new java.awt.Color(30, 15, 79));
        Label_DatPhong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_DatPhong.setForeground(new java.awt.Color(169, 170, 255));
        Label_DatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Users-2.24.png"))); // NOI18N
        Label_DatPhong.setText("   Đặt phòng");
        Label_DatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_DatPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_DatPhongMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_DatPhongLayout = new javax.swing.GroupLayout(Panel_DatPhong);
        Panel_DatPhong.setLayout(Panel_DatPhongLayout);
        Panel_DatPhongLayout.setHorizontalGroup(
            Panel_DatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DatPhongLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(Label_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_DatPhongLayout.setVerticalGroup(
            Panel_DatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_DatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Panel_CheckIn.setBackground(new java.awt.Color(30, 15, 79));

        Label_Checkin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Checkin.setForeground(new java.awt.Color(169, 170, 255));
        Label_Checkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Users-2.24.png"))); // NOI18N
        Label_Checkin.setText("   Check in");
        Label_Checkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_CheckinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_CheckinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_CheckInLayout = new javax.swing.GroupLayout(Panel_CheckIn);
        Panel_CheckIn.setLayout(Panel_CheckInLayout);
        Panel_CheckInLayout.setHorizontalGroup(
            Panel_CheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_CheckInLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(Label_Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_CheckInLayout.setVerticalGroup(
            Panel_CheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Checkin, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Panel_CheckOut.setBackground(new java.awt.Color(30, 15, 79));

        Label_Checkout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Checkout.setForeground(new java.awt.Color(169, 170, 255));
        Label_Checkout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Users-2.24.png"))); // NOI18N
        Label_Checkout.setText("   Check out");
        Label_Checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_CheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_CheckoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_CheckOutLayout = new javax.swing.GroupLayout(Panel_CheckOut);
        Panel_CheckOut.setLayout(Panel_CheckOutLayout);
        Panel_CheckOutLayout.setHorizontalGroup(
            Panel_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_CheckOutLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(Label_Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_CheckOutLayout.setVerticalGroup(
            Panel_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Checkout, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Panel_TaiKhoan.setBackground(new java.awt.Color(30, 15, 79));

        Label_TaiKhoan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_TaiKhoan.setForeground(new java.awt.Color(169, 170, 255));
        Label_TaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Users-2.24.png"))); // NOI18N
        Label_TaiKhoan.setText("   Tài khoản");
        Label_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_TaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_TaiKhoanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_TaiKhoanLayout = new javax.swing.GroupLayout(Panel_TaiKhoan);
        Panel_TaiKhoan.setLayout(Panel_TaiKhoanLayout);
        Panel_TaiKhoanLayout.setHorizontalGroup(
            Panel_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TaiKhoanLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(Label_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_TaiKhoanLayout.setVerticalGroup(
            Panel_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Thanh_Fix_Panel.setBackground(new java.awt.Color(30, 15, 79));

        Thanh_Fix_Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Thanh_Fix_Label.setForeground(new java.awt.Color(255, 255, 255));
        Thanh_Fix_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Thanh_Fix_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Thanh_Fix_LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Thanh_Fix_PanelLayout = new javax.swing.GroupLayout(Thanh_Fix_Panel);
        Thanh_Fix_Panel.setLayout(Thanh_Fix_PanelLayout);
        Thanh_Fix_PanelLayout.setHorizontalGroup(
            Thanh_Fix_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Thanh_Fix_PanelLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(Thanh_Fix_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Thanh_Fix_PanelLayout.setVerticalGroup(
            Thanh_Fix_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Thanh_Fix_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Panel_Logout.setBackground(new java.awt.Color(30, 15, 79));
        Panel_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_LogoutMouseClicked(evt);
            }
        });

        Lable_LogOut.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Lable_LogOut.setForeground(new java.awt.Color(169, 170, 255));
        Lable_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Users-2.24.png"))); // NOI18N
        Lable_LogOut.setText("   Đăng xuất");
        Lable_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lable_LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lable_LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lable_LogOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_LogoutLayout = new javax.swing.GroupLayout(Panel_Logout);
        Panel_Logout.setLayout(Panel_LogoutLayout);
        Panel_LogoutLayout.setHorizontalGroup(
            Panel_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LogoutLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(Lable_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_LogoutLayout.setVerticalGroup(
            Panel_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lable_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Quanlyphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Quanlykhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Quanlydichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Dattiec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thanh_Fix_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(Panel_TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Quanlyphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Quanlykhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Quanlydichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Dattiec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Thanh_Fix_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainView_Panel.setBackground(new java.awt.Color(30, 15, 79));
        MainView_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 255), 3, true));
        MainView_Panel.setPreferredSize(new java.awt.Dimension(883, 667));

        javax.swing.GroupLayout MainView_PanelLayout = new javax.swing.GroupLayout(MainView_Panel);
        MainView_Panel.setLayout(MainView_PanelLayout);
        MainView_PanelLayout.setHorizontalGroup(
            MainView_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
        );
        MainView_PanelLayout.setVerticalGroup(
            MainView_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );

        jPanel4.setOpaque(false);

        jSeparator3.setBackground(new java.awt.Color(137, 77, 238));
        jSeparator3.setForeground(new java.awt.Color(30, 15, 79));

        Search_Text2.setFont(new java.awt.Font("Arial Narrow", 2, 14)); // NOI18N
        Search_Text2.setForeground(new java.awt.Color(137, 64, 231));
        Search_Text2.setText("Search...");
        Search_Text2.setBorder(null);
        Search_Text2.setOpaque(false);
        Search_Text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Text2ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Search.24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search_Text2)
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Search_Text2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainView_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(549, 549, 549)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainView_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_TrangChuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_TrangChuMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_TrangChuMouseMoved

    private void Label_TrangchuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_TrangchuMouseExited
//        Label_Trangchu.setForeground(Color.getColor());
    }//GEN-LAST:event_Label_TrangchuMouseExited

    private void Panel_TrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_TrangChuMouseEntered

    }//GEN-LAST:event_Panel_TrangChuMouseEntered

    private void Panel_TrangChuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_TrangChuMouseDragged

    }//GEN-LAST:event_Panel_TrangChuMouseDragged

    private void Panel_TrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_TrangChuMouseExited

    }//GEN-LAST:event_Panel_TrangChuMouseExited

    private void Label_TrangchuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_TrangchuMouseEntered
//        Label_Trangchu.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_TrangchuMouseEntered

    private void Label_QuanlyphongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_QuanlyphongMouseEntered
//        Label_Quanlyphong.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_QuanlyphongMouseEntered

    private void Label_QuanlyphongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_QuanlyphongMouseExited
//        Label_Quanlyphong.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_QuanlyphongMouseExited

    private void Label_QuanlykhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_QuanlykhachhangMouseEntered
//        Label_Quanlykhachhang.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_QuanlykhachhangMouseEntered

    private void Label_QuanlykhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_QuanlykhachhangMouseExited
//        Label_Quanlykhachhang.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_QuanlykhachhangMouseExited

    private void Label_QuanlydichvuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_QuanlydichvuMouseEntered
//        Label_Quanlydichvu.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_QuanlydichvuMouseEntered

    private void Label_QuanlydichvuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_QuanlydichvuMouseExited
//        Label_Quanlydichvu.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_QuanlydichvuMouseExited

    private void Label_DatTiecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_DatTiecMouseEntered
//        Label_DatTiec.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_DatTiecMouseEntered

    private void Label_DatTiecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_DatTiecMouseExited
//        Label_DatTiec.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_DatTiecMouseExited

    private void Label_DatPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_DatPhongMouseEntered
//        Label_DatPhong.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_DatPhongMouseEntered

    private void Label_DatPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_DatPhongMouseExited
//        Label_DatPhong.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_DatPhongMouseExited

    private void Label_CheckinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CheckinMouseEntered
//        Label_Checkin.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_CheckinMouseEntered

    private void Label_CheckinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CheckinMouseExited
//        Label_Checkin.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_CheckinMouseExited

    private void Label_CheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CheckoutMouseEntered
//        Label_Checkout.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_CheckoutMouseEntered

    private void Label_CheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CheckoutMouseExited
//        Label_Checkout.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_CheckoutMouseExited

    private void Label_TaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_TaiKhoanMouseEntered
//        Label_TaiKhoan.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_TaiKhoanMouseEntered

    private void Label_TaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_TaiKhoanMouseExited
//        Label_TaiKhoan.setForeground(Color.WHITE);
    }//GEN-LAST:event_Label_TaiKhoanMouseExited

    private void Thanh_Fix_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Thanh_Fix_LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Thanh_Fix_LabelMouseExited

    private void Thanh_Fix_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Thanh_Fix_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Thanh_Fix_LabelMouseEntered

    private void Search_Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_Text2ActionPerformed

    private void Lable_LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lable_LogOutMouseEntered
//        Lable_LogOut.setForeground(Color.WHITE);
        Border border = BorderFactory.createMatteBorder(0, 4, 0, 0, Color.getHSBColor(0.76666665f, 1.0f, 1.0f));
        Panel_Logout.setBorder(border);
    }//GEN-LAST:event_Lable_LogOutMouseEntered

    private void Lable_LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lable_LogOutMouseExited
        Panel_Logout.setBorder(null);
    }//GEN-LAST:event_Lable_LogOutMouseExited

    private void Panel_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_LogoutMouseClicked

    }//GEN-LAST:event_Panel_LogoutMouseClicked

    private void Lable_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lable_LogOutMouseClicked
        this.dispose();
        new Logout_controller();
    }//GEN-LAST:event_Lable_LogOutMouseClicked
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Checkin;
    private javax.swing.JLabel Label_Checkout;
    private javax.swing.JLabel Label_DatPhong;
    private javax.swing.JLabel Label_DatTiec;
    private javax.swing.JLabel Label_Quanlydichvu;
    private javax.swing.JLabel Label_Quanlykhachhang;
    private javax.swing.JLabel Label_Quanlyphong;
    private javax.swing.JLabel Label_TaiKhoan;
    private javax.swing.JLabel Label_Trangchu;
    private javax.swing.JLabel Lable_LogOut;
    private javax.swing.JPanel MainView_Panel;
    private javax.swing.JPanel Panel_CheckIn;
    private javax.swing.JPanel Panel_CheckOut;
    private javax.swing.JPanel Panel_DatPhong;
    private javax.swing.JPanel Panel_Dattiec;
    private javax.swing.JPanel Panel_Logout;
    private javax.swing.JPanel Panel_Quanlydichvu;
    private javax.swing.JPanel Panel_Quanlykhachhang;
    private javax.swing.JPanel Panel_Quanlyphong;
    private javax.swing.JPanel Panel_TaiKhoan;
    private javax.swing.JPanel Panel_TrangChu;
    private javax.swing.JTextField Search_Text2;
    private javax.swing.JLabel Thanh_Fix_Label;
    private javax.swing.JPanel Thanh_Fix_Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
